### ISSUE TITLE
Installing Escort did not work 

### ISSUE THREAD

**Issue by adelpinoherrera** [xiaorudong/Escort#1]
Hello,

I am trying to install Escort so I can use the Shinny app and I followed these steps:
if (!requireNamespace("remotes", quietly = TRUE))
  install.packages("remotes")

remotes::install_github("xiaorudong/Escort")

remotes::install_bitbucket("scLCA/single_cell_lca")

Everything seemed to work correctly but whenever I run install.packages('Escort') I get an error saying that Escort is not available for this version of R. I am currently using R 4.3.2.
What R version should I use to install the packages?

**Comment by xiaorudong** [comment]
Hello,

Thanks for trying out the Escort package. There's no need to use install.packages('Escort') after you've successfully installed it from GitHub using remotes::install_github("xiaorudong/Escort"). This method directly installs the package into your R environment, bypassing CRAN, which is why install.packages can't find it.

After installation, you can directly load the package along with others needed for the shiny app:

```
library(Escort)
library(scLCA)
library(shiny)
library(shinydashboard)
Escort::shinyEscort()
```

I hope this clarifies the process. If you have further questions, feel free to ask.

**Comment by adelpinoherrera** [comment]
Hi Xiaoru,

I did run Library(Escort) and I get an error message saying that there is no package called Escort. However, I am able to import all the other packages with the library command. Maybe something went wrong during the installation process, would you happen to know what could have gone wrong?


All the best,



Adriana Del Pino Herrera (she/they)

PhD Student | Biomedical Engineering

BEAT Cancer Lab | University of Florida

Vice-president, BME GSC

President, BME Inclusive Excellence

J Crayton Pruitt Family Department of Biomedical Engineering

Phone: 412-417-1815

[cid:f0d7b5a4-fb17-4620-87a7-f19f737f8f99][cid:bfabaa3d-91d8-49f5-adbf-3477f5339733]
________________________________

**Comment by xiaorudong** [comment]
Hey Adriana,

It seems there was an issue during the installation process. Could you please rerun `remotes::install_github("xiaorudong/Escort")` and check the output for any error messages? Installation errors can prevent the package from being properly installed. If any errors appear and you're unsure how to resolve them, feel free to paste them here. I'm here to help!

**Comment by adelpinoherrera** [comment]
Hi Xiaoru,

Thank you for the advice. I reran that line and I got the following message.

Skipping 8 packages not available: slingshot, SingleCellExperiment, S4Vectors, org.Mm.eg.db, org.Hs.eg.db, limma, edgeR, clusterProfiler

I also keep getting message about some of those packages are not available for my version of R. What R did you use to develop the Escort package?


All the best,



Adriana Del Pino Herrera (she/they)

PhD Student | Biomedical Engineering

BEAT Cancer Lab | University of Florida

Vice-president, BME GSC

President, BME Inclusive Excellence

J Crayton Pruitt Family Department of Biomedical Engineering

Phone: 412-417-1815

[cid:af28b5bd-d7c3-46a5-8064-82afd3cc7d8f][cid:6d4e344e-1a5f-488a-a44f-c34ebb4fc4fa]
________________________________

**Comment by xiaorudong** [comment]
Hello Adriana,

Thank you for bringing this to our attention. When I initially developed the Escort package, I used an older version of R. Since then, I have updated to R version 4.3.2, the same version you are using. I've noticed that the eight packages you mentioned, which cannot be installed, are hosted on Bioconductor. 

To address this issue, you can manually install these Bioconductor packages using the `BiocManager::install()` function. I will take a closer look at the dependencies and update our Escort package as soon as possible to ensure better compatibility and prevent similar issues in the future. Thank you for using our package.

**Comment by adelpinoherrera** [comment]
Hi Xiaoru,

Thank you so much. I installed the packages via BiocManager::install() and loaded them using library(). However, once again when I run library(Escort) it tells me that the package does not exist.

What version of R did you develop the package in? I am trying to use your package through hipergator so I can open a session in the appropriate version of R. Thank youuu


All the best,



Adriana Del Pino Herrera (she/they)

PhD Student | Biomedical Engineering

BEAT Cancer Lab | University of Florida

Vice-president, BME GSC

President, BME Inclusive Excellence

J Crayton Pruitt Family Department of Biomedical Engineering

Phone: 412-417-1815

[cid:d7a67503-1fd8-46c6-b621-b49e926a8c85][cid:7b4136f7-6b2b-4526-bd43-db493b52de10]
________________________________

**Comment by xiaorudong** [comment]
Hello Adriana,

The Escort package was initially developed with R version 4.1.2. However, for all recent testing and updates, I have transitioned to using R version 4.3.2 to ensure compatibility with newer R environments.

**Comment by adelpinoherrera** [comment]
Hi Xiaoru,

Do you then recommend that I try to use Escort on the 4.3.2 version even though I am not sure what is wrong with the installation or should I try it on the 4.1.2 version to see if it works there?


All the best,



Adriana Del Pino Herrera (she/they)

PhD Student | Biomedical Engineering

BEAT Cancer Lab | University of Florida

Vice-president, BME GSC

President, BME Inclusive Excellence

J Crayton Pruitt Family Department of Biomedical Engineering

Phone: 412-417-1815

[cid:7df4bb3d-c04e-4b25-8e67-c1cb3b90d31b][cid:1959831e-b56b-4e76-9c66-60ffa43b8ed3]
________________________________

**Comment by xiaorudong** [comment]
Hello Adriana,

Escort package should operate with R version 4.3.2. Could you please re-attempt the installation and share any messages or output that appear during the process? This will allow me to examine the details more closely and provide you with more targeted assistance to resolve any issues.

**Comment by adelpinoherrera** [comment]
Hi Xiaoru,

I got it to work! Sorry for the trouble with this. Do you have any tutorials on how to obtain the raw and normalized count data to input into the ShinyApp? I have the raw data for the project I want to work on but I am unsure on how to get it to the right format for the counts that the app requires. Thank you so much.


All the best,



Adriana Del Pino Herrera (she/they)

PhD Student | Biomedical Engineering

BEAT Cancer Lab | University of Florida

Vice-president, BME GSC

President, BME Inclusive Excellence

J Crayton Pruitt Family Department of Biomedical Engineering

Phone: 412-417-1815

[cid:302b6654-5f79-4da0-8775-834ccbe1231c][cid:1cff0b04-0c59-4778-9552-512de44c8915]
________________________________

**Comment by xiaorudong** [comment]
Hey Adriana,

Absolutely happy to know that everything is working now! For preparing your normalized count data for the ShinyApp, several normalization methods are commonly used in scRNA-seq data analysis. These include [SCTransform](https://satijalab.org/seurat/articles/sctransform_vignette.html) in the Seurat package and normalization functions in [Scran](https://bioconductor.org/packages/release/bioc/vignettes/scuttle/inst/doc/norm.html#3_Pooling_normalization). Please choose a method that suits your needs and follow the detailed steps provided in their respective tutorials. After normalization, you can export your data to a csv file, ensuring that rows represent genes and columns represent cells, aligning with the structure of your raw dataset.

If you're working with a particularly large dataset, I recommend considering our R package, which is faster and more flexible. We've provided a detailed [vignette](https://www.rhondabacher.com/vignettes/Escort.html) to guide you through this process.
